### ISSUE TITLE
Error: ENOENT: no such file or directory, stat '{GUID}.zip'

### ISSUE THREAD

**Issue by VADemon** [dddExperiments/PhotosynthDownloader#10]
I'm using your mass downloader and this error keeps crashing the downloads from time to time.

```
Downloading synth 95a96b53-3a29-4f71-8ab2-f4e45ac34ab9
fs.js:844
  return binding.stat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, stat 'part-00001_job_temp/95a96b53-3a29-4f71-8ab2-f4e45ac34ab9.zip'
    at Error (native)
    at Object.fs.statSync (fs.js:844:18)
    at Object.statSync (/media/vademon/542a5cbf-7446-4b34-b943-79790153d8b5/photosynth-grab/PhotosynthDownloader/node_modules/graceful-fs/polyfills.js:297:22)
    at Object.copySync (/media/vademon/542a5cbf-7446-4b34-b943-79790153d8b5/photosynth-grab/PhotosynthDownloader/node_modules/fs-extra/lib/copy-sync/copy-sync.js:27:84)
    at /media/vademon/542a5cbf-7446-4b34-b943-79790153d8b5/photosynth-grab/PhotosynthDownloader/synth_mass_downloader.js:93:13
    at ChildProcess.exithandler (child_process.js:204:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by dddExperiments** [comment]
Which OS are you using?

The mass downloader is a bit complicated.
For maximum performance I'm downloading first to a temp folder (ram disk) and then the folder is zipped inside temp and copied to output folder.
It looks like the copy from temp to output is failing in your case (disk space issues?).

**Comment by dddExperiments** [comment]
I've updated the synth_mass_downloader.js script to skip synth when the zip archives is not found.
This is a workaround, not a proper fix.

**Comment by dddExperiments** [comment]
Closing issue as photosynth.net is down now.
