### ISSUE TITLE
Error: ENOTDIR: not a directory

### ISSUE THREAD

**Issue by kannes** [dddExperiments/PhotosynthDownloader#8]
Trying random UUIDs I got this error:

```
$ node synth_downloader.js b71b2e22-d614-4ba8-9d8d-6b728dc77f8b output
Downloading photosynth: b71b2e22-d614-4ba8-9d8d-6b728dc77f8b to output
1 comments downloaded.
Downloading 3 images.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOTDIR: not a directory, mkdir '/tmp/PhotosynthDownloader/output/b71b2e22-d614-4ba8-9d8d-6b728dc77f8b/images/m01001200-AUkP_+K_gyM/0.dzi/11'
    at Object.fs.mkdirSync (fs.js:855:18)
    at Object.mkdirsSync (/tmp/PhotosynthDownloader/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:29:9)
    at /tmp/PhotosynthDownloader/ps1_downloader.js:326:13
    at /tmp/PhotosynthDownloader/downloadable_object.js:162:5
    at Parser.<anonymous> (/tmp/PhotosynthDownloader/node_modules/xml2js/lib/xml2js.js:489:18)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at SAXParser.onclosetag (/tmp/PhotosynthDownloader/node_modules/xml2js/lib/xml2js.js:447:26)
    at emit (/tmp/PhotosynthDownloader/node_modules/sax/lib/sax.js:640:35)
    at emitNode (/tmp/PhotosynthDownloader/node_modules/sax/lib/sax.js:645:5)

```

**Comment by dddExperiments** [comment]
I assume you are trying from Unix/MacOsX?
It looks like there is a path issue in my script: / vs \.
If you have access to a windows machine please use my script on windows.
I will fix the script by testing on Ubuntu but as the deadline is Monday I would recommend you to use it on Windows (it works: I've downloaded this synth).

**Comment by kannes** [comment]
Thanks! It is supposed to remove "\0.dzi" from the path on Windows I guess? So on Linux it should remove "/0.dzi"? I will try that.

**Comment by dddExperiments** [comment]
I've fixed the issue (it took me longer to install node on Ubuntu than fixing the issue :-( . 
Using node 0.10.x which was installed by default on Ubuntu is actually causing other type of trouble unrelated. You should use node 6.9.5 instead.
